name: Autograding

on:
  push:
    branches:
      - main

jobs:
  testElectronicDevice:
    name: Test ElectronicDevice Class
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build -x test
      - name: Run ElectronicDevice tests
        run: ./gradlew test --tests "com.example.ElectronicDeviceTest"

  testSmartphone:
    name: Test Smartphone Class
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build -x test
      - name: Run Smartphone tests
        run: ./gradlew test --tests "com.example.SmartphoneTest"

  testBonus:
    name: Test Bonus Features
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build -x test
      - name: Run Bonus tests
        run: ./gradlew test --tests "com.example.BonusTest"
